import 'package:flutter/material.dart';import 'package:sanket_s_application1/core/app_export.dart';double get strokeAlignInside =>  BorderSide.strokeAlignInside;double get strokeAlignCenter =>  BorderSide.strokeAlignCenter;double get strokeAlignOutside =>  BorderSide.strokeAlignOutside;class AppDecoration {static BoxDecoration get background =>  BoxDecoration(color: appTheme.gray50);
static BoxDecoration get fillCyan =>  BoxDecoration(color: appTheme.cyan300);
static BoxDecoration get fillCyan30002 =>  BoxDecoration(color: appTheme.cyan30002);
static BoxDecoration get fillCyan30003 =>  BoxDecoration(color: appTheme.cyan30003);
static BoxDecoration get fillGray =>  BoxDecoration(color: appTheme.gray900);
static BoxDecoration get fillOnError =>  BoxDecoration(color: theme.colorScheme.onError);
static BoxDecoration get fillWhiteA =>  BoxDecoration(color: appTheme.whiteA700);
static BoxDecoration get gradientCyan30002ToPrimary =>  BoxDecoration(gradient: LinearGradient(begin: Alignment(-0.26, -0.31), end: Alignment(1.14, 1.51), colors: [appTheme.cyan30002.withOpacity(0.37), theme.colorScheme.primary.withOpacity(0.37)]));
static BoxDecoration get gradientCyanToPrimary =>  BoxDecoration(gradient: LinearGradient(begin: Alignment(-0.26, -0.31), end: Alignment(1.14, 1.51), colors: [appTheme.cyan30002, theme.colorScheme.primary]));
static BoxDecoration get gradientGrayToGray =>  BoxDecoration(gradient: LinearGradient(begin: Alignment(0.5, 0), end: Alignment(0.5, 0.53), colors: [appTheme.gray50, appTheme.gray50.withOpacity(0)]));
static BoxDecoration get outline =>  BoxDecoration();
static BoxDecoration get outlineGray =>  BoxDecoration(border: Border.all(color: appTheme.gray900, width: 1.h));
static BoxDecoration get outlineGray900 =>  BoxDecoration();
static BoxDecoration get outlineOnPrimaryContainer =>  BoxDecoration(border: Border.all(color: theme.colorScheme.onPrimaryContainer.withOpacity(0.1), width: 1.h));
static BoxDecoration get outlineOnPrimaryContainer1 =>  BoxDecoration(color: appTheme.whiteA700, boxShadow: [BoxShadow(color: theme.colorScheme.onPrimaryContainer.withOpacity(0.05), spreadRadius: 2.h, blurRadius: 2.h, offset: Offset(0, 1))]);
static BoxDecoration get outlineRedA =>  BoxDecoration(border: Border.all(color: appTheme.redA100, width: 1.h));
 }
class BorderRadiusStyle {static BorderRadius get circleBorder112 =>  BorderRadius.circular(112.h);
static BorderRadius get circleBorder147 =>  BorderRadius.circular(147.h);
static BorderRadius get roundedBorder12 =>  BorderRadius.circular(12.h);
static BorderRadius get roundedBorder144 =>  BorderRadius.circular(144.h);
static BorderRadius get roundedBorder16 =>  BorderRadius.circular(16.h);
static BorderRadius get roundedBorder20 =>  BorderRadius.circular(20.h);
static BorderRadius get roundedBorder223 =>  BorderRadius.circular(223.h);
static BorderRadius get roundedBorder24 =>  BorderRadius.circular(24.h);
static BorderRadius get roundedBorder28 =>  BorderRadius.circular(28.h);
static BorderRadius get roundedBorder32 =>  BorderRadius.circular(32.h);
static BorderRadius get roundedBorder333 =>  BorderRadius.circular(333.h);
static BorderRadius get roundedBorder4 =>  BorderRadius.circular(4.h);
static BorderRadius get roundedBorder78 =>  BorderRadius.circular(78.h);
static BorderRadius get roundedBorder8 =>  BorderRadius.circular(8.h);
 }
