import 'package:flutter_switch/flutter_switch.dart';import '../../core/app_export.dart';import '../../widgets/app_bar/appbar_leading_iconbutton.dart';import '../../widgets/app_bar/appbar_subtitle_two.dart';import '../../widgets/app_bar/custom_app_bar.dart';import 'models/living_room_model.dart';import 'provider/living_room_provider.dart';class LivingRoomScreen extends StatefulWidget {const LivingRoomScreen({Key? key}) : super(key: key);

@override LivingRoomScreenState createState() =>  LivingRoomScreenState();
static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => LivingRoomProvider(), child: LivingRoomScreen()); } 
 }
class LivingRoomScreenState extends State<LivingRoomScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: appTheme.whiteA700, appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 39.v), child: Container(padding: EdgeInsets.symmetric(horizontal: 32.h), child: Column(children: [Opacity(opacity: 0.8, child: Text("lbl_living_room".tr, style: theme.textTheme.headlineMedium)), SizedBox(height: 49.v), _buildLivingRoomDoorOne(context), SizedBox(height: 20.v), _buildLivingRoomProfile(context), SizedBox(height: 20.v), _buildLivingRoomSofaWithArmrest(context), SizedBox(height: 20.v), _buildLivingRoomFlag(context), SizedBox(height: 20.v), _buildLivingRoomLightBulb(context), SizedBox(height: 20.v), _buildLivingRoomRealEstateOne(context)])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 88.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 32.h), onTap: () {onTapArrowLeft(context);}), actions: [AppbarSubtitleTwo(text: "lbl_skip".tr, margin: EdgeInsets.fromLTRB(32.h, 13.v, 32.h, 21.v))]); } 
/// Section Widget
Widget _buildLivingRoomDoorOne(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(height: 83.adaptSize, width: 83.adaptSize, padding: EdgeInsets.all(24.h), decoration: AppDecoration.gradient.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: CustomImageView(imagePath: ImageConstant.imgDoor134x34, height: 34.adaptSize, width: 34.adaptSize, alignment: Alignment.center)), Padding(padding: EdgeInsets.only(left: 24.h, top: 16.v, bottom: 16.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Opacity(opacity: 0.4, child: Text("lbl_connected".tr, style: CustomTextStyles.bodySmallOnPrimaryContainer12)), SizedBox(height: 2.v), Opacity(opacity: 0.6, child: Text("lbl_door".tr, style: theme.textTheme.titleLarge))])), Spacer(), Padding(padding: EdgeInsets.only(top: 27.v, bottom: 26.v), child: Selector<LivingRoomProvider, bool?>(selector: (context, provider) => provider.isSelectedSwitch, builder: (context, isSelectedSwitch, child) {return FlutterSwitch(value: isSelectedSwitch ?? false, height: 30.h, width: 63.h, toggleSize: 24, borderRadius: 15.h, inactiveColor: appTheme.gray900, inactiveToggleColor: appTheme.gray900.withOpacity(0.49), onToggle: (value) {context.read<LivingRoomProvider>().changeSwitchBox1(value);});}))]); } 
/// Section Widget
Widget _buildLivingRoomProfile(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(height: 83.adaptSize, width: 83.adaptSize, padding: EdgeInsets.all(24.h), decoration: AppDecoration.black.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Opacity(opacity: 0.6, child: CustomImageView(imagePath: ImageConstant.imgProfile, height: 34.adaptSize, width: 34.adaptSize, alignment: Alignment.center))), Padding(padding: EdgeInsets.only(left: 24.h, top: 16.v, bottom: 16.v), child: _buildSeven(context, disconnectedText: "lbl_disconnected".tr, sofaText: "lbl_chair".tr)), Spacer(), Padding(padding: EdgeInsets.only(top: 27.v, bottom: 26.v), child: Selector<LivingRoomProvider, bool?>(selector: (context, provider) => provider.isSelectedSwitch1, builder: (context, isSelectedSwitch1, child) {return FlutterSwitch(value: isSelectedSwitch1 ?? false, height: 30.h, width: 63.h, toggleSize: 24, borderRadius: 15.h, inactiveColor: appTheme.gray900, inactiveToggleColor: appTheme.gray900.withOpacity(0.49), onToggle: (value) {context.read<LivingRoomProvider>().changeSwitchBox2(value);});}))]); } 
/// Section Widget
Widget _buildLivingRoomSofaWithArmrest(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(height: 83.adaptSize, width: 83.adaptSize, padding: EdgeInsets.all(24.h), decoration: AppDecoration.gradient.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: CustomImageView(imagePath: ImageConstant.imgSofaWithArmrest, height: 34.adaptSize, width: 34.adaptSize, alignment: Alignment.center)), Padding(padding: EdgeInsets.only(left: 24.h, top: 16.v, bottom: 16.v), child: _buildSeven(context, disconnectedText: "lbl_disconnected".tr, sofaText: "lbl_sofa".tr)), Spacer(), Padding(padding: EdgeInsets.only(top: 27.v, bottom: 26.v), child: Selector<LivingRoomProvider, bool?>(selector: (context, provider) => provider.isSelectedSwitch2, builder: (context, isSelectedSwitch2, child) {return FlutterSwitch(value: isSelectedSwitch2 ?? false, height: 30.h, width: 63.h, toggleSize: 24, borderRadius: 15.h, inactiveColor: appTheme.gray900, inactiveToggleColor: appTheme.gray900.withOpacity(0.49), onToggle: (value) {context.read<LivingRoomProvider>().changeSwitchBox3(value);});}))]); } 
/// Section Widget
Widget _buildLivingRoomFlag(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(height: 83.adaptSize, width: 83.adaptSize, padding: EdgeInsets.all(24.h), decoration: AppDecoration.black.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Opacity(opacity: 0.6, child: CustomImageView(imagePath: ImageConstant.imgFlagGray900, height: 34.adaptSize, width: 34.adaptSize, alignment: Alignment.center))), Padding(padding: EdgeInsets.only(left: 24.h, top: 16.v, bottom: 16.v), child: _buildSeven(context, disconnectedText: "lbl_disconnected".tr, sofaText: "lbl_ac".tr)), Spacer(), Padding(padding: EdgeInsets.only(top: 27.v, bottom: 26.v), child: Selector<LivingRoomProvider, bool?>(selector: (context, provider) => provider.isSelectedSwitch3, builder: (context, isSelectedSwitch3, child) {return FlutterSwitch(value: isSelectedSwitch3 ?? false, height: 30.h, width: 63.h, toggleSize: 24, borderRadius: 15.h, inactiveColor: appTheme.gray900, inactiveToggleColor: appTheme.gray900.withOpacity(0.49), onToggle: (value) {context.read<LivingRoomProvider>().changeSwitchBox4(value);});}))]); } 
/// Section Widget
Widget _buildLivingRoomLightBulb(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(height: 83.adaptSize, width: 83.adaptSize, padding: EdgeInsets.all(24.h), decoration: AppDecoration.black.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Opacity(opacity: 0.6, child: CustomImageView(imagePath: ImageConstant.imgLightBulbGray900, height: 34.adaptSize, width: 34.adaptSize, alignment: Alignment.center))), Padding(padding: EdgeInsets.only(left: 24.h, top: 16.v, bottom: 13.v), child: _buildSeven(context, disconnectedText: "lbl_disconnected".tr, sofaText: "lbl_lamp".tr)), Spacer(), Padding(padding: EdgeInsets.only(top: 27.v, bottom: 26.v), child: Selector<LivingRoomProvider, bool?>(selector: (context, provider) => provider.isSelectedSwitch4, builder: (context, isSelectedSwitch4, child) {return FlutterSwitch(value: isSelectedSwitch4 ?? false, height: 30.h, width: 63.h, toggleSize: 24, borderRadius: 15.h, inactiveColor: appTheme.gray900, inactiveToggleColor: appTheme.gray900.withOpacity(0.49), onToggle: (value) {context.read<LivingRoomProvider>().changeSwitchBox5(value);});}))]); } 
/// Section Widget
Widget _buildLivingRoomRealEstateOne(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(height: 83.adaptSize, width: 83.adaptSize, padding: EdgeInsets.all(24.h), decoration: AppDecoration.black.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Opacity(opacity: 0.6, child: CustomImageView(imagePath: ImageConstant.imgRealEstate1, height: 34.adaptSize, width: 34.adaptSize, alignment: Alignment.center))), Padding(padding: EdgeInsets.only(left: 24.h, top: 17.v, bottom: 17.v), child: _buildSeven(context, disconnectedText: "lbl_disconnected".tr, sofaText: "lbl_window".tr)), Spacer(), Padding(padding: EdgeInsets.only(top: 27.v, bottom: 26.v), child: Selector<LivingRoomProvider, bool?>(selector: (context, provider) => provider.isSelectedSwitch5, builder: (context, isSelectedSwitch5, child) {return FlutterSwitch(value: isSelectedSwitch5 ?? false, height: 30.h, width: 63.h, toggleSize: 24, borderRadius: 15.h, inactiveColor: appTheme.gray900, inactiveToggleColor: appTheme.gray900.withOpacity(0.49), onToggle: (value) {context.read<LivingRoomProvider>().changeSwitchBox6(value);});}))]); } 
/// Common widget
Widget _buildSeven(BuildContext context, {required String disconnectedText, required String sofaText, }) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Opacity(opacity: 0.4, child: Text(disconnectedText, style: CustomTextStyles.bodySmallOnPrimaryContainer12.copyWith(color: theme.colorScheme.onPrimaryContainer))), SizedBox(height: 1.v), Opacity(opacity: 0.6, child: Text(sofaText, style: theme.textTheme.titleLarge!.copyWith(color: appTheme.gray900.withOpacity(0.56))))]); } 
/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
