import 'package:sanket_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:sanket_s_application1/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:sanket_s_application1/widgets/app_bar/appbar_subtitle_one.dart';import 'package:flutter/material.dart';import 'package:sanket_s_application1/core/app_export.dart';class MusicScreen extends StatelessWidget {const MusicScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: appTheme.whiteA700, appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 42.v), child: Column(children: [Opacity(opacity: 0.8, child: Text("Now Playing", style: CustomTextStyles.headlineSmallRegular)), SizedBox(height: 3.v), Opacity(opacity: 0.3, child: Text("Alec Benjamin", style: CustomTextStyles.titleMediumGray900)), SizedBox(height: 57.v), _buildNowPlaying(context), SizedBox(height: 58.v), Padding(padding: EdgeInsets.symmetric(horizontal: 79.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Opacity(opacity: 0.1, child: CustomImageView(imagePath: ImageConstant.imgGroup40, height: 17.v, width: 24.h, margin: EdgeInsets.only(top: 11.v, bottom: 12.v))), Spacer(flex: 50), IconButton(onPressed: () {}, constraints: BoxConstraints(minHeight: 41.adaptSize, minWidth: 41.adaptSize), padding: EdgeInsets.all(0), icon: Container(width: 41.adaptSize, height: 41.adaptSize, decoration: BoxDecoration(borderRadius: BorderRadius.circular(20.h), gradient: LinearGradient(begin: Alignment(-0.26, -0.31), end: Alignment(1.14, 1.51), colors: [appTheme.cyan30002, theme.colorScheme.primary])), padding: EdgeInsets.all(12.h), child: CustomImageView(imagePath: ImageConstant.imgCloseWhiteA700))), Spacer(flex: 49), Opacity(opacity: 0.1, child: CustomImageView(imagePath: ImageConstant.imgLocationGray900, height: 17.v, width: 24.h, margin: EdgeInsets.only(top: 11.v, bottom: 12.v)))])), SizedBox(height: 59.v), _buildTwentyFive(context)]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 88.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 32.h), onTap: () {onTapArrowLeft(context);}), actions: [AppbarSubtitleOne(text: "Demons", margin: EdgeInsets.fromLTRB(32.h, 15.v, 32.h, 13.v))]); } 
/// Section Widget
Widget _buildNowPlaying(BuildContext context) { return SizedBox(height: 291.v, width: 315.h, child: Stack(alignment: Alignment.centerLeft, children: [Align(alignment: Alignment.center, child: SizedBox(height: 285.v, width: 315.h, child: CircularProgressIndicator(value: 0.5))), Opacity(opacity: 0.8, child: CustomImageView(imagePath: ImageConstant.imgGroup85, height: 291.v, width: 166.h, alignment: Alignment.centerLeft)), Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(left: 116.h, right: 116.h, bottom: 90.v), child: Column(mainAxisSize: MainAxisSize.min, children: [Opacity(opacity: 0.8, child: Text("50%", style: theme.textTheme.displaySmall)), Opacity(opacity: 0.4, child: Text("Volume", style: CustomTextStyles.bodyLargeGray900_1))])))])); } 
/// Section Widget
Widget _buildTwentyFive(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 175.h, vertical: 40.v), decoration: AppDecoration.background.copyWith(borderRadius: BorderRadiusStyle.roundedBorder28), child: CustomImageView(imagePath: ImageConstant.imgArrowUp, height: 24.adaptSize, width: 24.adaptSize)); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
