import 'package:flutter_switch/flutter_switch.dart';import '../../core/app_export.dart';import '../../widgets/app_bar/appbar_leading_iconbutton.dart';import '../../widgets/app_bar/appbar_subtitle_two.dart';import '../../widgets/app_bar/custom_app_bar.dart';import 'notifier/kitchen_room_notifier.dart';class KitchenRoomScreen extends ConsumerStatefulWidget {const KitchenRoomScreen({Key? key}) : super(key: key);

@override KitchenRoomScreenState createState() =>  KitchenRoomScreenState();
 }
class KitchenRoomScreenState extends ConsumerState<KitchenRoomScreen> {@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: appTheme.whiteA700, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 32.h, vertical: 36.v), child: Column(children: [Opacity(opacity: 0.8, child: Text("lbl_kitchen_room".tr, style: theme.textTheme.headlineMedium)), SizedBox(height: 52.v), _buildStoveOne(context), SizedBox(height: 20.v), _buildFlag(context), SizedBox(height: 20.v), _buildToasterOne(context), SizedBox(height: 20.v), _buildFlag1(context), SizedBox(height: 62.v), _buildMore(context), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 88.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 32.h), onTap: () {onTapArrowLeft(context);}), actions: [AppbarSubtitleTwo(text: "lbl_skip".tr, margin: EdgeInsets.fromLTRB(32.h, 13.v, 32.h, 21.v))]); } 
/// Section Widget
Widget _buildStoveOne(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(height: 83.adaptSize, width: 83.adaptSize, padding: EdgeInsets.all(24.h), decoration: AppDecoration.gradient.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: CustomImageView(imagePath: ImageConstant.imgStove1, height: 34.adaptSize, width: 34.adaptSize, alignment: Alignment.center)), Padding(padding: EdgeInsets.only(left: 24.h, top: 16.v, bottom: 16.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Opacity(opacity: 0.4, child: Text("lbl_connected".tr, style: CustomTextStyles.bodySmallOnPrimaryContainer12)), SizedBox(height: 2.v), Opacity(opacity: 0.6, child: Text("lbl_gas_stove".tr, style: theme.textTheme.titleLarge))])), Spacer(), Padding(padding: EdgeInsets.only(top: 27.v, bottom: 26.v), child: Consumer(builder: (context, ref, _) {return FlutterSwitch(value: ref.watch(kitchenRoomNotifier).isSelectedSwitch ?? false, height: 30.h, width: 63.h, toggleSize: 24, borderRadius: 15.h, inactiveColor: appTheme.gray900, inactiveToggleColor: appTheme.gray900.withOpacity(0.49), onToggle: (value) {ref.read(kitchenRoomNotifier.notifier).changeSwitchBox1(value);});}))]); } 
/// Section Widget
Widget _buildFlag(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(height: 83.adaptSize, width: 83.adaptSize, padding: EdgeInsets.all(24.h), decoration: AppDecoration.black.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Opacity(opacity: 0.6, child: CustomImageView(imagePath: ImageConstant.imgFlagGray90034x34, height: 34.adaptSize, width: 34.adaptSize, alignment: Alignment.center))), Padding(padding: EdgeInsets.only(left: 24.h, top: 16.v, bottom: 16.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Opacity(opacity: 0.4, child: Text("lbl_disconnected".tr, style: CustomTextStyles.bodySmallOnPrimaryContainer12)), SizedBox(height: 1.v), Opacity(opacity: 0.6, child: Text("lbl_microwafe".tr, style: theme.textTheme.titleLarge))])), Spacer(), Padding(padding: EdgeInsets.only(top: 27.v, bottom: 26.v), child: Consumer(builder: (context, ref, _) {return FlutterSwitch(value: ref.watch(kitchenRoomNotifier).isSelectedSwitch1 ?? false, height: 30.h, width: 63.h, toggleSize: 24, borderRadius: 15.h, inactiveColor: appTheme.gray900, inactiveToggleColor: appTheme.gray900.withOpacity(0.49), onToggle: (value) {ref.read(kitchenRoomNotifier.notifier).changeSwitchBox2(value);});}))]); } 
/// Section Widget
Widget _buildToasterOne(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(height: 83.adaptSize, width: 83.adaptSize, padding: EdgeInsets.all(24.h), decoration: AppDecoration.gradient.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: CustomImageView(imagePath: ImageConstant.imgToaster1, height: 34.adaptSize, width: 34.adaptSize, alignment: Alignment.center)), Padding(padding: EdgeInsets.only(left: 24.h, top: 16.v, bottom: 16.v), child: _buildNine(context, disconnectedText: "lbl_disconnected".tr, acText: "lbl_toaster".tr)), Spacer(), Padding(padding: EdgeInsets.only(top: 27.v, bottom: 26.v), child: Consumer(builder: (context, ref, _) {return FlutterSwitch(value: ref.watch(kitchenRoomNotifier).isSelectedSwitch2 ?? false, height: 30.h, width: 63.h, toggleSize: 24, borderRadius: 15.h, inactiveColor: appTheme.gray900, inactiveToggleColor: appTheme.gray900.withOpacity(0.49), onToggle: (value) {ref.read(kitchenRoomNotifier.notifier).changeSwitchBox3(value);});}))]); } 
/// Section Widget
Widget _buildFlag1(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(height: 83.adaptSize, width: 83.adaptSize, padding: EdgeInsets.all(24.h), decoration: AppDecoration.black.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Opacity(opacity: 0.6, child: CustomImageView(imagePath: ImageConstant.imgFlagGray900, height: 34.adaptSize, width: 34.adaptSize, alignment: Alignment.center))), Padding(padding: EdgeInsets.only(left: 24.h, top: 16.v, bottom: 16.v), child: _buildNine(context, disconnectedText: "lbl_disconnected".tr, acText: "lbl_ac".tr)), Spacer(), Padding(padding: EdgeInsets.only(top: 27.v, bottom: 26.v), child: Consumer(builder: (context, ref, _) {return FlutterSwitch(value: ref.watch(kitchenRoomNotifier).isSelectedSwitch3 ?? false, height: 30.h, width: 63.h, toggleSize: 24, borderRadius: 15.h, inactiveColor: appTheme.gray900, inactiveToggleColor: appTheme.gray900.withOpacity(0.49), onToggle: (value) {ref.read(kitchenRoomNotifier.notifier).changeSwitchBox4(value);});}))]); } 
/// Section Widget
Widget _buildMore(BuildContext context) { return Row(mainAxisSize: MainAxisSize.min, children: [Expanded(child: Container(width: 236.h, height: 60.v, decoration: BoxDecoration(borderRadius: BorderRadius.circular(14.h), gradient: LinearGradient(begin: Alignment(-0.26, -0.31), end: Alignment(1.14, 1.51), colors: [appTheme.cyan30002, theme.colorScheme.primary])), child: ElevatedButton(style: ElevatedButton.styleFrom(backgroundColor: Colors.transparent, side: BorderSide.none, shape: RoundedRectangleBorder(borderRadius: BorderRadius.zero), padding: EdgeInsets.zero, elevation: 0), onPressed: () {}, child: Text("lbl_more".tr, style: CustomTextStyles.titleMediumWhiteA70016)))), CustomImageView(imagePath: ImageConstant.imgArrowRightGray900, height: 14.adaptSize, width: 14.adaptSize, margin: EdgeInsets.only(left: 28.h, top: 23.v, bottom: 23.v))]); } 
/// Common widget
Widget _buildNine(BuildContext context, {required String disconnectedText, required String acText, }) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Opacity(opacity: 0.4, child: Text(disconnectedText, style: CustomTextStyles.bodySmallOnPrimaryContainer12.copyWith(color: theme.colorScheme.onPrimaryContainer))), SizedBox(height: 2.v), Opacity(opacity: 0.6, child: Text(acText, style: theme.textTheme.titleLarge!.copyWith(color: appTheme.gray900.withOpacity(0.56))))]); } 
/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
