import '../../core/app_export.dart';import '../window_page/window_page.dart';import 'notifier/window_tab_container_notifier.dart';class WindowTabContainerScreen extends ConsumerStatefulWidget {const WindowTabContainerScreen({Key? key}) : super(key: key);

@override WindowTabContainerScreenState createState() =>  WindowTabContainerScreenState();
 }

// ignore_for_file: must_be_immutable
class WindowTabContainerScreenState extends ConsumerState<WindowTabContainerScreen> with  TickerProviderStateMixin {late TabController tabviewController;

@override void initState() { super.initState(); tabviewController = TabController(length: 4, vsync: this); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: appTheme.whiteA700, body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 53.v), Expanded(child: SingleChildScrollView(child: Column(children: [_buildArrowLeftRow(context), SizedBox(height: 40.v), _buildTabview(context), SizedBox(height: 566.v, child: TabBarView(controller: tabviewController, children: [WindowPage(), WindowPage(), WindowPage(), WindowPage()]))])))])))); } 
/// Section Widget
Widget _buildArrowLeftRow(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 31.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [IconButton(onPressed: () {onPressArrowLeft(context);}, constraints: BoxConstraints(minHeight: 56.adaptSize, minWidth: 56.adaptSize), padding: EdgeInsets.all(0), icon: Container(width: 56.adaptSize, height: 56.adaptSize, decoration: BoxDecoration(color: appTheme.gray50, borderRadius: BorderRadius.circular(12.h)), padding: EdgeInsets.all(21.h), child: CustomImageView(imagePath: ImageConstant.imgArrowLeft))), Padding(padding: EdgeInsets.symmetric(vertical: 2.v), child: Column(crossAxisAlignment: CrossAxisAlignment.end, children: [Opacity(opacity: 0.8, child: Text("lbl_window".tr, style: theme.textTheme.titleMedium)), SizedBox(height: 3.v), Opacity(opacity: 0.4, child: Text("lbl_living_room2".tr, style: CustomTextStyles.bodyMediumGray900))]))])); } 
/// Section Widget
Widget _buildTabview(BuildContext context) { return Container(height: 96.v, width: 311.h, child: TabBar(controller: tabviewController, labelPadding: EdgeInsets.zero, tabs: [Tab(child: Column(children: [Container(height: 63.adaptSize, width: 63.adaptSize, padding: EdgeInsets.all(19.h), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Opacity(opacity: 0.2, child: CustomImageView(imagePath: ImageConstant.imgLightBulbGray900, height: 24.adaptSize, width: 24.adaptSize, alignment: Alignment.center))), Opacity(opacity: 0.6, child: Padding(padding: EdgeInsets.only(top: 15.v), child: Text("lbl_lights".tr)))])), Tab(child: Column(children: [Container(height: 63.adaptSize, width: 63.adaptSize, padding: EdgeInsets.all(19.h), decoration: AppDecoration.background.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Opacity(opacity: 0.2, child: CustomImageView(imagePath: ImageConstant.imgTelevision, height: 24.adaptSize, width: 24.adaptSize, alignment: Alignment.center))), Opacity(opacity: 0.6, child: Padding(padding: EdgeInsets.only(top: 13.v), child: Text("lbl_tv".tr)))])), Tab(child: Column(children: [Container(height: 63.adaptSize, width: 63.adaptSize, padding: EdgeInsets.all(19.h), decoration: AppDecoration.background.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Opacity(opacity: 0.2, child: CustomImageView(imagePath: ImageConstant.imgScienceThermometer, height: 24.adaptSize, width: 24.adaptSize, alignment: Alignment.center))), Opacity(opacity: 0.6, child: Padding(padding: EdgeInsets.only(top: 15.v), child: Text("lbl_temp".tr)))])), Tab(child: Column(children: [Container(height: 63.adaptSize, width: 63.adaptSize, padding: EdgeInsets.all(19.h), decoration: AppDecoration.gradient.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: CustomImageView(imagePath: ImageConstant.imgRealEstate124x24, height: 24.adaptSize, width: 24.adaptSize, alignment: Alignment.center)), Padding(padding: EdgeInsets.only(top: 13.v), child: Text("lbl_window".tr))]))])); } 
/// Common widget
Widget _buildTelevision(BuildContext context, {required String television, required String tV, }) { return Column(children: [Container(height: 63.adaptSize, width: 63.adaptSize, padding: EdgeInsets.all(19.h), decoration: AppDecoration.background.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Opacity(opacity: 0.2, child: CustomImageView(imagePath: television, height: 24.adaptSize, width: 24.adaptSize, alignment: Alignment.center))), SizedBox(height: 13.v), Opacity(opacity: 0.6, child: Text(tV, style: CustomTextStyles.labelLargeGray900Medium.copyWith(color: appTheme.gray900.withOpacity(0.56))))]); } 
/// Navigates back to the previous screen.
onPressArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
