import 'package:sanket_s_application1/presentation/window_page/window_page.dart';import 'package:flutter/material.dart';import 'package:sanket_s_application1/core/app_export.dart';class WindowTabContainerScreen extends StatefulWidget {const WindowTabContainerScreen({Key? key}) : super(key: key);

@override WindowTabContainerScreenState createState() =>  WindowTabContainerScreenState();
 }

// ignore_for_file: must_be_immutable
class WindowTabContainerScreenState extends State<WindowTabContainerScreen> with  TickerProviderStateMixin {late TabController tabviewController;

@override void initState() { super.initState(); tabviewController = TabController(length: 4, vsync: this); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: appTheme.whiteA700, body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 53.v), Expanded(child: SingleChildScrollView(child: Column(children: [_buildArrowLeftSection(context), SizedBox(height: 40.v), _buildTabview(context), SizedBox(height: 566.v, child: TabBarView(controller: tabviewController, children: [WindowPage(), WindowPage(), WindowPage(), WindowPage()]))])))])))); } 
/// Section Widget
Widget _buildArrowLeftSection(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 31.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [IconButton(onPressed: () {onPressArrowLeft(context);}, constraints: BoxConstraints(minHeight: 56.adaptSize, minWidth: 56.adaptSize), padding: EdgeInsets.all(0), icon: Container(width: 56.adaptSize, height: 56.adaptSize, decoration: BoxDecoration(color: appTheme.gray50, borderRadius: BorderRadius.circular(12.h)), padding: EdgeInsets.all(21.h), child: CustomImageView(imagePath: ImageConstant.imgArrowLeft))), Padding(padding: EdgeInsets.symmetric(vertical: 2.v), child: Column(crossAxisAlignment: CrossAxisAlignment.end, children: [Opacity(opacity: 0.8, child: Text("Window", style: theme.textTheme.titleMedium)), SizedBox(height: 3.v), Opacity(opacity: 0.4, child: Text("Living Room", style: CustomTextStyles.bodyMediumGray900))]))])); } 
/// Section Widget
Widget _buildTabview(BuildContext context) { return Container(height: 96.v, width: 311.h, child: TabBar(controller: tabviewController, labelPadding: EdgeInsets.zero, tabs: [Tab(child: Column(children: [IconButton(onPressed: () {}, constraints: BoxConstraints(minHeight: 63.adaptSize, minWidth: 63.adaptSize), padding: EdgeInsets.all(0), icon: Container(width: 63.adaptSize, height: 63.adaptSize, decoration: BoxDecoration(color: appTheme.gray5001, borderRadius: BorderRadius.circular(12.h)), padding: EdgeInsets.all(19.h), child: CustomImageView(imagePath: ImageConstant.imgBrightness))), Opacity(opacity: 0.6, child: Padding(padding: EdgeInsets.only(top: 15.v), child: Text("Lights")))])), Tab(child: Column(children: [IconButton(onPressed: () {}, constraints: BoxConstraints(minHeight: 63.adaptSize, minWidth: 63.adaptSize), padding: EdgeInsets.all(0), icon: Container(width: 63.adaptSize, height: 63.adaptSize, decoration: BoxDecoration(color: appTheme.gray50, borderRadius: BorderRadius.circular(12.h)), padding: EdgeInsets.all(19.h), child: CustomImageView(imagePath: ImageConstant.imgTelevision))), Opacity(opacity: 0.6, child: Padding(padding: EdgeInsets.only(top: 13.v), child: Text("TV")))])), Tab(child: Column(children: [IconButton(onPressed: () {}, constraints: BoxConstraints(minHeight: 63.adaptSize, minWidth: 63.adaptSize), padding: EdgeInsets.all(0), icon: Container(width: 63.adaptSize, height: 63.adaptSize, decoration: BoxDecoration(color: appTheme.gray50, borderRadius: BorderRadius.circular(12.h)), padding: EdgeInsets.all(19.h), child: CustomImageView(imagePath: ImageConstant.imgScienceThermometer))), Opacity(opacity: 0.6, child: Padding(padding: EdgeInsets.only(top: 15.v), child: Text("Temp")))])), Tab(child: Column(children: [IconButton(onPressed: () {}, constraints: BoxConstraints(minHeight: 63.adaptSize, minWidth: 63.adaptSize), padding: EdgeInsets.all(0), icon: Container(width: 63.adaptSize, height: 63.adaptSize, decoration: BoxDecoration(borderRadius: BorderRadius.circular(12.h), gradient: LinearGradient(begin: Alignment(-0.26, -0.31), end: Alignment(1.14, 1.51), colors: [appTheme.cyan30002, theme.colorScheme.primary])), padding: EdgeInsets.all(19.h), child: CustomImageView(imagePath: ImageConstant.imgRealEstate163x63))), Padding(padding: EdgeInsets.only(top: 13.v), child: Text("Window"))]))])); } 
/// Common widget
Widget _buildTelevision(BuildContext context, {required String tV, }) { return Column(children: [IconButton(onPressed: () {}, constraints: BoxConstraints(minHeight: 63.adaptSize, minWidth: 63.adaptSize), padding: EdgeInsets.all(0), icon: Container(width: 63.adaptSize, height: 63.adaptSize, decoration: BoxDecoration(color: appTheme.gray50, borderRadius: BorderRadius.circular(12.h)), padding: EdgeInsets.all(19.h), child: CustomImageView(imagePath: ImageConstant.imgTelevision))), SizedBox(height: 13.v), Opacity(opacity: 0.6, child: Text(tV, style: CustomTextStyles.labelLargeGray900Medium.copyWith(color: appTheme.gray900.withOpacity(0.56))))]); } 

/// Navigates back to the previous screen.
onPressArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
