import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/menulist">MenuList</Link>
        </li>
        <li>
          <Link to="/customer">Customer</Link>
        </li>
        <li>
          <Link to="/review">Review</Link>
        </li>
        <li>
          <Link to="/orderlist">OrderList</Link>
        </li>
        <li>
          <Link to="/orderid">OrderId</Link>
        </li>
        <li>
          <Link to="/addtable">AddTable</Link>
        </li>
        <li>
          <Link to="/analytics">Analytics</Link>
        </li>
        <li>
          <Link to="/categoriesnine">CategoriesNine</Link>
        </li>
        <li>
          <Link to="/tableid">TableId</Link>
        </li>
        <li>
          <Link to="/tablelist">TableList</Link>
        </li>
        <li>
          <Link to="/dashboard">Dashboard</Link>
        </li>
        <li>
          <Link to="/addmenu">AddMenu</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
