import 'package:smooth_page_indicator/smooth_page_indicator.dart';import '../../core/app_export.dart';import 'models/onboarding_model.dart';import 'provider/onboarding_provider.dart';class OnboardingScreen extends StatefulWidget {const OnboardingScreen({Key? key}) : super(key: key);

@override OnboardingScreenState createState() =>  OnboardingScreenState();
static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => OnboardingProvider(), child: OnboardingScreen()); } 
 }
class OnboardingScreenState extends State<OnboardingScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: appTheme.whiteA700, body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 32.h, vertical: 51.v), child: Column(children: [SizedBox(height: 9.v), SizedBox(height: 10.v, child: AnimatedSmoothIndicator(activeIndex: 0, count: 3, effect: ScrollingDotsEffect(spacing: 24, activeDotColor: appTheme.cyan30002, dotColor: appTheme.cyan30002.withOpacity(0.42), activeDotScale: 1.25, dotHeight: 8.v, dotWidth: 8.h))), SizedBox(height: 40.v), CustomImageView(imagePath: ImageConstant.imgRectangle4, height: 451.v, width: 311.h, radius: BorderRadius.circular(24.h)), SizedBox(height: 36.v), Opacity(opacity: 0.8, child: Container(width: 255.h, margin: EdgeInsets.symmetric(horizontal: 27.h), child: Text("msg_technologically".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.bodyLarge18.copyWith(height: 1.56)))), SizedBox(height: 7.v), Opacity(opacity: 0.6, child: Container(width: 254.h, margin: EdgeInsets.symmetric(horizontal: 27.h), child: Text("msg_lorem_ipsum_dolor".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.labelLargeGray900Bold.copyWith(height: 1.83))))])), bottomNavigationBar: _buildSwipeRightArrow(context))); } 
/// Section Widget
Widget _buildSwipeRightArrow(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 148.h, right: 148.h, bottom: 35.v), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Opacity(opacity: 0.2, child: Text("lbl_swipe_right".tr, style: theme.textTheme.bodySmall)), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 12.adaptSize, width: 12.adaptSize, margin: EdgeInsets.only(left: 7.h, bottom: 2.v))])); } 
 }
