import 'package:sanket_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:sanket_s_application1/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:sanket_s_application1/widgets/app_bar/appbar_title.dart';import 'package:flutter/material.dart';import 'package:sanket_s_application1/core/app_export.dart';class ConnectingScreen extends StatelessWidget {const ConnectingScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: appTheme.whiteA700, body: Container(height: SizeUtils.height, width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 40.v), child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.only(left: 32.h, top: 13.v, right: 32.h), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildAppBar(context), SizedBox(height: 70.v), Opacity(opacity: 0.8, child: Text("JBL BIG STREAM", style: CustomTextStyles.titleMediumOnPrimaryContainer16)), SizedBox(height: 5.v), Opacity(opacity: 0.6, child: Text("Speaker", style: CustomTextStyles.bodyLargeOnPrimaryContainer_1)), Spacer(), Container(padding: EdgeInsets.symmetric(horizontal: 30.h, vertical: 18.v), width: 311.h, decoration: BoxDecoration(borderRadius: BorderRadius.circular(14.h), gradient: LinearGradient(begin: Alignment(-0.26, -0.31), end: Alignment(1.14, 1.51), colors: [appTheme.cyan30002, theme.colorScheme.primary])), child: Text("Connect", style: CustomTextStyles.titleMediumWhiteA70016))]))), CustomImageView(imagePath: ImageConstant.imgImage15, height: 467.v, width: 375.h, alignment: Alignment.bottomCenter, margin: EdgeInsets.only(bottom: 74.v)), CustomImageView(imagePath: ImageConstant.imgImage16, height: 467.v, width: 375.h, alignment: Alignment.bottomCenter, margin: EdgeInsets.only(bottom: 74.v))])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 88.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 32.h), onTap: () {onTapArrowLeft(context);}), title: AppbarTitle(text: "Search to connect", margin: EdgeInsets.only(left: 85.h))); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
